### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by mgoodness** [glerchundi/setup-etcd-peers-environment#1]
Would you be interested in extending infra-helper to generate the etcd-peer list based on a user-provided AWS tag name/value? That would be useful to those of us who spin up individual etcd nodes instead of an ASG.

Thanks!

**Comment by glerchundi** [comment]
@mgoodness, i'm not using infra-helper anymore. I decided to separate this project in pieces. For now just the etcd2-bootstrapper is available in https://github.com/glerchundi/etcd2-bootstrapper, it's being used in my terraform scripts with CoreOS: https://github.com/glerchundi/infrastructure-etcd2/blob/master/files/etcd.yml.

It allows you to decide if you want dynamic or static etcd2 configuration.
